### ISSUE TITLE
Bug? Inconsistent behavior between Gremlin as string and Fluent api on edge population of Vertex object.

### ISSUE THREAD

**Issue by zifnab87** [datastax/java-dse-graph#1]
I saw this discrepancy between Datastax Studio (which worked) and my code that uses the fluent api which didn't
```
 GraphStatement st1 = new SimpleGraphStatement("g.V().has(\"uuid\",\"uniqueid\").next().edges(Direction.IN,\"CreatedBy\").hasNext()");
    GraphStatement st2 = new SimpleGraphStatement("g.V().has(\"uuid\",\"uniqueid\").inE(\"CreatedBy\").hasNext()");
    System.out.println(dseSession.executeGraph(st1.setGraphName("graph")).one()); //returns true
    System.out.println(dseSession.executeGraph(st2.setGraphName("graph")).one()); //returns true
    System.out.println(g.V().has("uuid","uniqueid").next().edges(Direction.IN,"CreatedBy").hasNext()); //returns false
    System.out.println(g.V().has("uuid","uniqueid").inE("CreatedBy").hasNext()); //returns true
```
Thank you

https://datastax-oss.atlassian.net/browse/JAVA-1250?focusedCommentId=38411&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-38411

**Comment by adutra** [comment]
Hi @zifnab87 thank you for reporting this issue. I see you also reported it on our Jira system, which is indeed the preferred way to discuss issues related to this project. I will be disabling issues on this project very shortly. Thanks!
